server:
  port: 8910

spring:
  application:
    name: usercenter
  cloud:
    nacos:
      discovery:
        # 指定nacos地址
        server-addr: 192.168.8.100
        # 集群
        cluster-name: gfs
    sentinel:
      transport:
        # 指定sentinel控制台地址
        dashboard: localhost:8879
  # MySQL数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.100:4002/gaofenshuo_dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 200
      max-wait: 60000
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKZcha4jRSw9yZX3YKE1ByufscakNRxQkPcnCtguJn9k0xGml9iQvHvCDkLsHIlaFlZ+qCtXsM6fMwte8ZOMEeUCAwEAAQ==
      filter:
        config:
          enabled: true
      filters: stat,wall,config
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        login-username: gaofenshuo
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        #allow:
        #deny:
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

feign:
  sentinel:
    # 开启熔断
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
  httpclient:
    enabled: true
    # feign最大连接数
    max-connections: 200
    # feign单个路由最大连接数
    max-connections-per-route: 50


ribbon:
  eager-load:
    enabled: true
    # 为哪些客户端开启饥饿加载，多个客户端使用逗号分隔（非必须）
    clients: usercenter, taskcenter, contentcenter

# feign和ribbon结合，指定策略。feign默认的是轮询的策略，这里的配置可以自定义
taskcenter:
  ribbon:
    NFLoadBalancerRuleClassName: com.dw.gfs.usercenter.feign.rule.MyRule

rocketmq:
  name-server: localhost:9876
  producer:
    # 小坑：必须指定group
    group: test-group

management:
  endpoints:
    web:
      exposure:
        include: "*"

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl