server:
  port: 8910

spring:
  application:
    name: usercenter
  cloud:
    nacos:
      discovery:
        # 指定nacos地址
        server-addr: localhost:8848
        # 集群
        cluster-name: gfs

feign:
  sentinel:
    # 开启熔断
    enabled: true

ribbon:
  eager-load:
    enabled: true
    # 为哪些客户端开启饥饿加载，多个客户端使用逗号分隔（非必须）
    clients: usercenter, taskcenter, contentcenter

# feign和ribbon结合，指定策略。feign默认的是轮询的策略，这里的配置可以自定义
taskcenter:
  ribbon:
    NFLoadBalancerRuleClassName: com.dw.gfs.usercenter.feign.rule.MyRule

rocketmq:
  name-server: localhost:9876
  producer:
    # 小坑：必须指定group
    group: test-group

management:
  endpoints:
    web:
      exposure:
        include: "*"