server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # 路由网关配置
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true

# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug

gfs:
  # 访问白名单
  white-list:
    - /token/*
    - /user/login