server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # 路由网关配置
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
    sentinel:
      transport:
        dashboard: localhost:8879
      eager: true

# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug

gfs:
  path:
    # 访问白名单
    white:
      usercenter:
        - /token/**
        - /msg/**
        - /s/**
      contentcenter:
        - /query/**