server:
  port: 8920

spring:
  application:
    name: contentcenter
  cloud:
    nacos:
      discovery:
        # 指定nacos地址
        server-addr: 192.168.8.100
        # 集群
        cluster-name: gfs
feign:
  sentinel:
    # 开启熔断
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"