server:
  port: 8930

spring:
  application:
    name: taskcenter
  cloud:
    nacos:
      discovery:
        # 指定nacos地址
        server-addr: 192.168.8.100:8848
        # 集群
        cluster-name: gfs
feign:
  sentinel:
    # 开启熔断
    enabled: true

rocketmq:
  name-server: localhost:9876

management:
  endpoints:
    web:
      exposure:
        include: "*"